apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-app
  labels:
    app: jupyter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-app
  template:
    metadata:
      labels:
        app: jupyter-app
    spec:
      volumes:
      - name: jupyter-volume
        hostPath:
            path: /run/desktop/mnt/host/c/jupyter-app-volume
            type: DirectoryOrCreate
      containers:
      - name: jupyter
        image: jupyter-app:v1.0
        imagePullPolicy: Never
        command: ["/usr/bin/bash"]
        args : ["jupyter lab --ip=0.0.0.0 --port=8888 --no-browser"]
        volumeMounts:
        - mountPath: /home/jovyan/data
          name: jupyter-volume



     